kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openresty-claim
  namespace: volumes-sample
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
