apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-nfs
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /var/k8s/logs/static-pv
    server: 172.16.16.8
  persistentVolumeReclaimPolicy: Retain
